catalog:
  '@ant-design/icons': ^6.0.0
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@antfu/eslint-config': ^4.13.2
  '@ctrl/tinycolor': ^4.1.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@eslint-react/eslint-plugin': ^1.50.0
  '@iconify/react': ^6.0.0
  '@reduxjs/toolkit': ^2.8.2
  '@types/lodash': ^4.17.17
  '@types/node': ^22.15.21
  '@types/react': ^19.1.5
  '@types/react-dom': ^19.1.5
  '@types/react-transition-group': ^4.4.12
  '@unocss/eslint-config': ^66.1.2
  '@unocss/preset-rem-to-px': ^66.1.2
  '@unocss/reset': ^66.1.2
  '@unocss/transformer-attributify-jsx': ^66.1.2
  '@vitejs/plugin-react': ^4.5.0
  antd: ^5.25.3
  axios: ^1.9.0
  clsx: ^2.1.1
  cropperjs: ~1.6.0
  dayjs: ^1.11.13
  dotenv: ^16.5.0
  eslint: ^9.27.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  framer-motion: ^12.13.0
  lodash: ^4.17.21
  rc-virtual-list: ^3.18.6
  react: ^19.1.0
  react-content-loader: ^7.0.2
  react-cropper: ^2.3.3
  react-device-detect: ^2.2.3
  react-dom: ^19.1.0
  react-error-boundary: ^6.0.0
  react-loader-spinner: ^6.1.6
  react-photo-view: ^1.2.7
  react-redux: ^9.2.0
  react-router: ^7.6.1
  react-transition-group: ^4.4.5
  redux-persist: ^6.0.0
  rollup-plugin-visualizer: ^6.0.0
  typescript: ^5.8.3
  unocss: ^66.1.2
  unocss-preset-scrollbar: ^3.2.0
  vite: ^6.3.5
  vite-plugin-compression: ^0.5.1
  vite-plugin-imagemin: ^0.6.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - cwebp-bin
  - esbuild
  - gifsicle
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - unrs-resolver
